version: 0.2

env:
  variables:
     NODE_ENV: "production"
     WEBPACK_BUILD_MODE: "production"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://${DeployBucket}/
      - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./dist/index.html s3://${DeployBucket}/
artifacts:
  files:
    - '**/*'
  base-directory: dist